App\Entity\Task:
    type: entity
    repositoryClass: App\Repository\TaskRepository
    table: tasks
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
        email:
            type: string
        status:
            type: string
        description:
            type: text
        editedBy:
            type: text